#!/usr/bin/env python3
"""
export_porymap.py - export every learned brush to tools/hack/porymap_scripts/autotile_rules.js
so the Porymap auto-tile/decorate scripts use exactly the same rules as mapbuild.py.

  python3 tools/hack/mapgen/export_porymap.py

Run it after `autotile.py learn <brush>`.
"""

import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import autotile  # noqa: E402
import pokemap  # noqa: E402

OUT = os.path.join(pokemap.ROOT, "tools/hack/porymap_scripts/autotile_rules.js")


def main():
    brushes = {}
    for path in sorted(glob.glob(os.path.join(autotile.BRUSH_DIR, "*.json"))):
        if path.endswith(".rules.json"):
            continue
        b = autotile.load_brush(path)
        r = autotile.load_rules(b)
        classes = {}
        for cname, c in b["classes"].items():
            code = autotile.class_code(b, cname)
            classes[code] = {
                "name": cname,
                "default": list(autotile.parse_block(c["default"])),
                "parity": c.get("parity", True),
                "paintable": c.get("paintable", True),
                "anchor": autotile.parse_block(c["anchor"])[0] if "anchor" in c else None,
                "onlyNear": [{"classes": o["classes"], "tiles": [autotile.parse_block(t)[0] for t in o["tiles"]]}
                             for o in c.get("only_near", [])],
            }
        member = {str(m): autotile.class_code(b, c) for m, c in b["_member_class"].items()}
        rules = {}
        for k, opts in r["rules"].items():
            rules[k] = [[*autotile.parse_block(blk), n] for blk, n in opts]
        brushes["%s/%s" % (b["primary"], b["secondary"])] = {
            "name": b["_name"], "classes": classes, "memberClass": member, "rules": rules,
        }
    with open(OUT, "w") as f:
        f.write("// GENERATED by tools/hack/mapgen/export_porymap.py - do not edit by hand.\n")
        f.write("// Auto-tile rules learned from vanilla maps (see docs/hack_tools.md).\n")
        f.write("export const BRUSHES = ")
        json.dump(brushes, f, separators=(",", ":"))
        f.write(";\n")
    print("wrote %s (%d brush(es), %d KB)" % (os.path.relpath(OUT, pokemap.ROOT), len(brushes), os.path.getsize(OUT) // 1024))


if __name__ == "__main__":
    main()
