DraconidVillage_House1_MapScripts::
	.byte 0


DraconidVillage_House1_EventScript_Weaver::
	msgbox DraconidVillage_House1_EventScript_Weaver_Text_0, MSGBOX_NPC
	return


DraconidVillage_House1_EventScript_Girl::
	msgbox DraconidVillage_House1_EventScript_Girl_Text_0, MSGBOX_NPC
	return


DraconidVillage_House1_EventScript_Weaver_Text_0:
	.string "Every tamer of the clan wears a scarf\n"
	.string "woven from dragon down.\p"
	.string "It keeps you warm on the peaks… and it\n"
	.string "tells other tamers where you come from.$"

DraconidVillage_House1_EventScript_Girl_Text_0:
	.string "Grandpa ELDER says the Guardian of the\n"
	.string "Sky lives above the clouds and never\l"
	.string "comes down.\p"
	.string "But then how does anyone know what it\n"
	.string "looks like?$"
