#!/usr/bin/env python3
"""
check_reputation.py - does every NPC the player can meet in the TEAM MAGMA uniform react to it?

  python3 tools/hack/check_reputation.py               # coverage per map + the total; exit 1 if an NPC is missing
  python3 tools/hack/check_reputation.py --missing     # the NPCs without a uniform branch (map, spot, script, line)
  python3 tools/hack/check_reputation.py --skipped     # what isn't counted, and why (by reason; -v lists them)
  python3 tools/hack/check_reputation.py --map Rustboro  # every object of the maps whose name contains the word
  python3 tools/hack/check_reputation.py --maps        # the maps that can / can't be entered in uniform
  python3 tools/hack/check_reputation.py --doc         # rewrite the generated part of docs/reputation_dialogue.md

"In uniform" is VAR_DRACONID_REPUTATION == REPUTATION_UNIFORM (D-103): from the recruitment in Petalburg Woods to
the Sootopolis turn. How the tool works it out (it reuses check_progression.py's simulator and tile search):

 1. Maps the player can enter in uniform: the v2 story (tools/hack/progression.json) is simulated leg by leg; for
    every leg whose simulated state has the uniform on, the tiles are flooded from where the player stands after
    the leg's scenes – collision, ledges, doors and warps, water / Strength / Rock Smash / Cut / Waterfall / Dive
    only with the HM *and* its badge, bike tiles only with a bike, objects whose hide flag is clear, coord
    triggers that turn the player back, Fly to every town whose Pokémon Center spot an earlier flood reached – and
    the scripts of the flooded maps' objects, signs and triggers that warp (the Safari Zone gate, Mr. Briney's
    boat, the Contest Hall, the Battle Tents …) are run on that state (items no story scene gives count as
    unknown), their destinations flooded as well. The union over the legs is "enterable in uniform"; everything
    else (the Battle Frontier, Ever Grande's upper terrace, the Sky Pillar, the Sootopolis Gym, the Trick House
    rooms behind its puzzle door, FRLG maps …) is skipped as "not enterable in uniform".
 2. Objects the player can meet there: shown on at least one of those legs after the map's load scripts ran (hide
    flag clear, or unknown to the simulator), and next to a flooded tile (or across a counter from one). Flags that
    only the scripts of people met there write (no story scene does) count as unknown, so people a side talk
    brings out (LANETTE at home, the WHITE HERB florist) are met too. Story objects hidden for the whole uniform
    period are skipped.
 3. What counts: people with a script. Skipped (with the reason): trainers (a trainer type, or a script that
    starts a trainer battle), item balls, berry trees, Cut trees / Rock Smash rocks / Strength boulders, other
    things (dolls, the egg stand, …), Pokémon (they only cry), and the few people in SKIP (each with its reason).
 4. Reacts = the code reachable from the object's script (goto, call, the conditional jumps, switch cases – so
    through an "@ Draconid Emerald" hook line in a vanilla script as well) compares VAR_DRACONID_REPUTATION
    with a REPUTATION_* state (a script that only asks "revealed?" is shown after the goods or the like, where
    the other answer is the uniform) or VAR_PLAYER_OUTFIT with PLAYER_OUTFIT_MAGMA, or the script is in
    UNIFORM_ONLY (a line only reachable in uniform and written to see it, D-255).

--doc writes the tables between the GENERATED markers of docs/reputation_dialogue.md from the reputation scripts
(data/scripts/draconid/reputation/*.pory) that the hand-written tables above the markers don't list yet: the
comment above each script (`// <who> at (x, y) (vanilla: "<line>")`, " – turns away" when it does) names the NPC,
the text labels the script shows give the Uniform / Revealed columns (a text whose name ends in "Uniform…" or
"Revealed…"; the rest of the name, if any, is shown in bold as the branch).
"""

import argparse
import glob
import json
import os
import re
import sys
import time

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools/hack"))
import check_progression as cp  # noqa: E402
import gen_script_doc as gsd  # noqa: E402

DOC = os.path.join(ROOT, "docs/reputation_dialogue.md")
REP_DIR = os.path.join(ROOT, "data/scripts/draconid/reputation")
DOC_BEGIN = "<!-- GENERATED by tools/hack/check_reputation.py --doc: edit the scripts, then rerun -->"
DOC_END = "<!-- END GENERATED -->"

# --- what isn't a person --------------------------------------------------------------------------------------
FIELD_SCRIPTS = {"EventScript_CutTree", "EventScript_RockSmash", "EventScript_StrengthBoulder"}
ITEM_SCRIPTS = {"Common_EventScript_FindItem"}
BERRY_SCRIPTS = {"BerryTreeScript"}
POKEMON_GFX = re.compile(r"OBJ_EVENT_GFX_(AZUMARILL|AZURILL|KECLEON|PIKACHU|POOCHYENA|SKITTY|WINGULL|ZIGZAGOON_\d|"
                         r"VIGOROTH_\w+|KYOGRE_\w+|GROUDON_\w+|RAYQUAZA_\w+|LATIAS|LATIOS|DEOXYS|MEW|LUGIA|HO_OH|"
                         r"KIRLIA|DUSCLOPS|SUDOWOODO|REGI\w*|SPECIES\(.*\))$")
THING_GFX = re.compile(r"OBJ_EVENT_GFX_(\w+_DOLL|BIRCHS_BAG|DRACONID_EGG_\w+|BALL_CUSHION|BIG_\w+|CUSHION_\w+|"
                       r"\w+_STATUE|FOSSIL|TRUCK|MOVING_BOX|MYSTERY_EVENT_DELIVERYMAN|SS_TIDAL|SUBMARINE_SHADOW|"
                       r"APPRENTICE|LINK_\w+_ANIM|LIGHT\w*|BIRTH_ISLAND_STONE|MR_BRINEYS_BOAT|\w+_BOAT|CABLE_CAR|"
                       r"QUESTION_MARK|ITEM_BALL)$")

# people who aren't counted, and why (script label -> reason)
LINK = "link room attendant: only met during a link"
SKIP = {
    "BattleColosseum_2P_EventScript_Attendant": LINK,
    "TradeCenter_EventScript_Attendant": LINK,
    "UnionRoom_EventScript_Attendant": LINK,
    "LilycoveCity_PokemonCenter_1F_EventScript_ContestLadyMon": "the CONTEST LADY's POKéMON (it only cries)",
    "MossdeepCity_SpaceCenter_1F_EventScript_MagmaNote": "TEAM MAGMA's notice on the wall, read like a sign",
    "Underwater_SeafloorCavern_EventScript_CheckStolenSub": "the stolen submarine, read like a sign",
}

# scripts only reached in uniform whose own lines already speak to it (the story's scenes, D-255 retexts)
ACT = "a story scene written for the uniform"
UNIFORM_ONLY = {
    # Act 1 / 2
    "PetalburgWoods_MagmaOutpost_EventScript_Courtney": "the outpost cabin welcomes the new grunt (its scripts.pory)",
    "PetalburgWoods_MagmaOutpost_EventScript_GruntM": "the outpost cabin welcomes the new grunt (its scripts.pory)",
    "PetalburgWoods_MagmaOutpost_EventScript_GruntF": "the outpost cabin welcomes the new grunt (its scripts.pory)",
    "RustboroCity_EventScript_Rival": ACT + ": BRENDAN at Rustboro's edge (act1.pory)",
    "RustboroCity_EventScript_DevonEmployee1": ACT + ": the DEVON GOODS chase (act2.pory, D-118, D-258)",
    "GraniteCave_StevensRoom_EventScript_Steven": ACT + ": STEVEN gets the LETTER (act2.pory)",
    "SlateportCity_OceanicMuseum_1F_EventScript_DraconidTabitha": ACT + ": TABITHA's museum order (act2.pory)",
    "SlateportCity_OceanicMuseum_1F_EventScript_FamiliarGrunt": ACT + ": NERINE's lookout (D-272)",
    "SlateportCity_OceanicMuseum_2F_EventScript_CaptStern": ACT + ": the museum raid (act2.pory)",
    "MauvilleCity_EventScript_Wally": ACT + ": WALLY's Mauville battle (act2.pory, D-236)",
    "MauvilleCity_EventScript_WallysUncle": ACT + ": WALLY's Mauville battle (act2.pory, D-236)",
    "VerdanturfTown_WandasHouse_EventScript_Wally": "retexted for the uniform (D-255)",
    "FallarborTown_CozmosHouse_EventScript_CozmosWife": "retexted for the uniform (D-255)",
    # Act 3
    "MtChimney_EventScript_Archie": ACT + ": MT. CHIMNEY (act3.pory)",
    "MtChimney_EventScript_Maxie": ACT + ": MT. CHIMNEY (act3.pory)",
    "MtChimney_EventScript_Tabitha": ACT + ": MT. CHIMNEY (act3.pory)",
    "MtChimney_EventScript_BusyMagmaGrunt3": "retexted for the uniform (\"Hey, rookie!\", D-255)",
    "LavaridgeTown_EventScript_DraconidTraveller": ACT + ": the Draconid traveller's MEGA STONE (act3.pory)",
    "Route112_EventScript_DraconidWally": ACT + ": WALLY's Route 112 battle (rivals2.pory, D-234)",
    # Act 4
    "Route119_EventScript_BridgeAquaGrunt1": "retexted for the uniform (the lookouts, D-255)",
    "Route119_EventScript_BridgeAquaGrunt2": "retexted for the uniform (the lookouts, D-255)",
    "Route119_EventScript_DraconidTabitha": ACT + ": TABITHA's Weather Institute order (act4.pory)",
    "Route119_WeatherInstitute_1F_EventScript_InstituteWorker2": ACT + ": the freed scientists (act4.pory)",
    "Route119_WeatherInstitute_2F_EventScript_WeatherScientist": ACT + ": the freed scientists (act4.pory)",
    "Route120_EventScript_Steven": ACT + ": STEVEN's DEVON SCOPE (D-275)",
    "Route120_EventScript_DraconidWally": ACT + ": WALLY's Route 120 battle (rivals2.pory, D-234)",
    "JaggedPass_EventScript_MagmaHideoutGuard": ACT + ": the hideout guard's rank test (act4.pory)",
    "MagmaHideout_4F_EventScript_Maxie": ACT + ": MAXIE's promotion (act4.pory)",
    # Act 5
    "AquaHideout_B2F_EventScript_Matt": ACT + ": NERINE in the AQUA HIDEOUT (act5.pory)",
    "AquaHideout_B2F_EventScript_DraconidNerine": ACT + ": NERINE in the AQUA HIDEOUT (act5.pory)",
    "MossdeepCity_SpaceCenter_1F_EventScript_Steven": ACT + ": STEVEN before the raid (act5.pory)",
    "MossdeepCity_SpaceCenter_2F_EventScript_Steven": ACT + ": the SPACE CENTER raid (act5.pory)",
    "MossdeepCity_SpaceCenter_2F_EventScript_Tabitha": ACT + ": the SPACE CENTER raid (act5.pory)",
    "MossdeepCity_SpaceCenter_2F_EventScript_DraconidRaid": ACT + ": the SPACE CENTER raid (act5.pory)",
    "MossdeepCity_SpaceCenter_2F_EventScript_DraconidCourtney": ACT + ": the SPACE CENTER raid (act5.pory)",
    "SeafloorCavern_Entrance_EventScript_Grunt": "retexted for the uniform (\"the MAGMA brat from the SPACE CENTER\", D-255)",
    "SootopolisCity_EventScript_Steven": ACT + ": STEVEN in the crisis (act5.pory)",
    "SootopolisCity_EventScript_DraconidTabitha": ACT + ": TABITHA's squad on the GYM island (act5.pory)",
    "SootopolisCity_EventScript_DraconidMagmaGrunt1": ACT + ": TABITHA's squad on the GYM island (act5.pory)",
    "SootopolisCity_EventScript_DraconidMagmaGrunt2": ACT + ": TABITHA's squad on the GYM island (act5.pory)",
}

REP_VAR = "VAR_DRACONID_REPUTATION"
REP_VALUES = {"REPUTATION_UNIFORM", "REPUTATION_PRE_UNIFORM", "REPUTATION_REVEALED"}
OUTFIT_VAR = "VAR_PLAYER_OUTFIT"
TRAINER_OPS = re.compile(r"^trainerbattle")


# ---------------------------------------------------------------------------------------------------------------
# 1 + 2: the maps and objects of the uniform period
# ---------------------------------------------------------------------------------------------------------------

def talkable(o, tiles, view):
    """can the player stand next to the object (or face it across a counter) on a flooded tile?"""
    x, y = o.get("cx", o["x"]), o.get("cy", o["y"])
    rx = int(o.get("movement_range_x") or 0)
    ry = int(o.get("movement_range_y") or 0)
    for ox in range(x - rx, x + rx + 1):
        for oy in range(y - ry, y + ry + 1):
            for dx, dy in cp.DIRS.values():
                if (ox + dx, oy + dy) in tiles:
                    return True
                mx, my = ox + dx, oy + dy
                if view.inside(mx, my) and view.beh[my * view.w + mx] == cp.COUNTER and (ox + 2 * dx, oy + 2 * dy) in tiles:
                    return True
    return False


class AnyItems(cp.Layer):
    """a bag where an item no story scene gave is unknown, not missing: a gate script's checkitem goes both ways"""
    __slots__ = ()

    def get(self, k, default=None):
        v = super().get(k, None)
        return cp.UNK if v is None else v

    def copy(self):
        return AnyItems(self.base, dict(self.diff))


class Period:
    """floods every uniform leg of the story; maps entered, objects shown"""

    def __init__(self, chk, verbose=False):
        self.chk = chk
        self.verbose = verbose
        self.maps = set()        # MAP_X entered in uniform
        self.visible = {}        # MAP_X -> {object index} shown on a uniform leg
        self.shown = {}          # MAP_X -> {object index} shown and next to a reachable tile
        self.legs = []           # leg ids in uniform
        self.states = []         # the simulated state after each of those legs' scenes
        self.tiles = {}          # MAP_X -> {(x, y)} flooded on any of them
        self.fly = set()         # MAP_X whose heal spot a flood reached
        self.warp_labels = self._warp_labels()
        table = json.load(open(cp.TABLE))
        self.rep = chk.sim.vkey(REP_VAR)
        self.uniform = chk.c.value("REPUTATION_UNIFORM")
        cp.run_story(chk, table, only="-", on_leg=self.on_leg)

    def _warp_labels(self):
        """script labels from which a warp command (or a warp special) is reachable"""
        s = self.chk.scripts
        warpy = set()
        for label in s.labels:
            for op, args in walk_cmds(s, label, limit=400):
                if op in cp.WARP_OPS or (op == "special" and args and args[0] in cp.SPECIAL_WARPS):
                    warpy.add(label)
                    break
        return warpy

    def on_leg(self, leg, st, pos):
        if st.var(self.rep) != self.uniform:
            return
        t0 = time.time()
        self.legs.append(leg.get("id"))
        st = st.flattened()
        self.states.append(st)
        srch = cp.Search(self.chk, st, set(self.fly))
        prev = {}
        frontier = []
        start = srch.node_at(*pos)
        if start is not None:
            frontier.append(start)
        frontier += srch.fly_nodes()
        tried = set()
        while frontier:
            self._flood(srch, frontier, prev)
            frontier = []
            for m in sorted({n[0] for n in prev}):
                for dest in self._script_warps(srch, m, tried):
                    n = srch.node_at(*dest)
                    if n is not None and n not in prev:
                        frontier.append(n)
        maps = {n[0] for n in prev}
        tiles = {n[:3] for n in prev}
        for h in self.chk.world.heal:
            if "respawn_map" in h and (h["map"], h["x"], h["y"]) in tiles:
                self.fly.add(h["map"])
        by_map = {}
        for n in prev:
            by_map.setdefault(n[0], set()).add((n[1], n[2]))
        for m in maps:
            self.tiles.setdefault(m, set()).update(by_map[m])
            v = srch.view(m)
            if v is not None:
                self.visible.setdefault(m, set()).update(o["index"] for o in v.objects)
                self.shown.setdefault(m, set()).update(o["index"] for o in v.objects if talkable(o, by_map[m], v))
        new = maps - self.maps
        self.maps |= maps
        if self.verbose:
            print("leg %-6s %-40s %4d maps (+%d) %.1fs" % (leg.get("id"), self.chk.world.pretty(pos[0]), len(maps),
                                                           len(new), time.time() - t0), file=sys.stderr)

    def _flood(self, srch, starts, prev):
        dq = []
        for s in starts:
            if s not in prev:
                prev[s] = None
                dq.append(s)
        i = 0
        while i < len(dq):
            n = dq[i]
            i += 1
            for nn, obs, how in srch.neighbors(n, set()):
                if obs or nn in prev:
                    continue
                prev[nn] = n
                dq.append(nn)

    def _script_warps(self, srch, map_id, tried):
        """where the warping scripts of a flooded map's objects, signs and coord triggers send the player"""
        v = srch.view(map_id)
        if v is None:
            return []
        runs = []
        for o in v.objects:
            if o.get("script") in self.warp_labels:
                runs.append((o["script"], o["index"]))
        for ev in v.md.bgs:
            if ev.get("script") in self.warp_labels:
                runs.append((ev["script"], 0))
        for evs in v.triggers.values():
            for ev in evs:
                if ev.get("script") in self.warp_labels:
                    runs.append((ev["script"], 0))
        out = []
        for label, idx in runs:
            key = (map_id, label)
            if key in tried:
                continue
            tried.add(key)
            ctx = cp.Ctx(map_id, last_talked=idx, budget=cp.SIDE_BUDGET)
            st = v.state.copy()
            st.items = AnyItems(st.items.base, dict(st.items.diff))  # side gifts (the Pokéblock Case) may be in the bag
            self.chk.sim.run(label, st, ctx)
            for w in ctx.warps:
                p = self.chk.warp_position(w)
                if p and p[0] in self.chk.world.maps:
                    out.append(p)
                    dv = srch.view(p[0])
                    if dv is not None and dv.inside(p[1], p[2]) and dv.tile(p[1], p[2])[0] in cp.STEP_WARP:
                        out.append((p[0], p[1], p[2] + 1))  # arriving on a door: the player steps out of it
        return out


# ---------------------------------------------------------------------------------------------------------------
# 3 + 4: what an object is, and whether it reacts
# ---------------------------------------------------------------------------------------------------------------

def walk_cmds(scripts, label, limit=4000):
    """(op, args) of every command reachable from label: goto/call, the conditional jumps, switch cases"""
    if label not in scripts.labels:
        return
    seen = set()
    todo = [scripts.labels[label]]
    n = len(scripts.cmds)
    count = 0
    while todo and count < limit:
        pc = todo.pop()
        while pc < n and pc not in seen and count < limit:
            seen.add(pc)
            count += 1
            op, args, _, _ = scripts.cmds[pc]
            yield op, args
            if op in ("goto", "call") or op.startswith(("goto_if", "call_if")) or op == "case":
                target = args[-1] if args else None
                if target in scripts.labels:
                    todo.append(scripts.labels[target])
                if op == "goto":
                    break
            if op in ("end", "return", "step_end", "releaseall_end"):
                break
            pc += 1


def straight_cmds(scripts, label, limit=60):
    """the commands run before the first branch (following plain gotos)"""
    out = []
    pc = scripts.labels.get(label)
    seen = set()
    while pc is not None and pc < len(scripts.cmds) and len(out) < limit and pc not in seen:
        seen.add(pc)
        op, args, _, _ = scripts.cmds[pc]
        out.append((op, args))
        if op == "goto":
            pc = scripts.labels.get(args[0]) if args else None
            continue
        if op in ("end", "return") or op.startswith(("goto_if", "call_if")) or op in ("switch", "case"):
            break
        pc += 1
    return out


def reacts(scripts, label):
    """True if code reachable from label branches on the uniform"""
    if label in UNIFORM_ONLY:
        return True
    switch_var = None
    for op, args in walk_cmds(scripts, label):
        if op == "switch":
            switch_var = args[0] if args else None
            continue
        if op == "case" and switch_var == REP_VAR and args and args[0] in REP_VALUES:
            return True
        if REP_VAR in args and REP_VALUES & set(args):
            return True
        if OUTFIT_VAR in args and "PLAYER_OUTFIT_MAGMA" in args:
            return True
    return False


def category(scripts, o):
    """None for a person to count, else why the object isn't counted"""
    s = o.get("script") or "0x0"
    g = o.get("graphics_id", "")
    if s in ("0x0", "NULL", ""):
        return "no script"
    if s in SKIP:
        return SKIP[s]
    if o.get("trainer_type") not in (None, "TRAINER_TYPE_NONE", "0"):
        return "trainer"
    if s in ITEM_SCRIPTS or g == "OBJ_EVENT_GFX_ITEM_BALL":
        return "item ball"
    if s in BERRY_SCRIPTS or "BERRY_TREE" in g:
        return "berry tree"
    if s in FIELD_SCRIPTS or g in cp.BOULDER + cp.ROCK + cp.TREE:
        return "Cut tree / Rock Smash rock / Strength boulder"
    if POKEMON_GFX.match(g):
        return "a Pokémon (it only cries)"
    if THING_GFX.match(g):
        return "a thing, not a person"
    if any(TRAINER_OPS.match(op) for op, _ in straight_cmds(scripts, s)):
        return "trainer"
    return None


class Coverage:
    def __init__(self, verbose=False):
        self.chk = cp.Checker()
        self.texts = text_index()
        self.period = Period(self.chk, verbose)
        self.rows = []  # (map name, object, verdict, reason)
        world = self.chk.world
        self.optional_talks()
        for md in sorted(world.maps.values(), key=lambda m: m.name):
            entered = md.id in self.period.maps
            shown = self.period.shown.get(md.id, set())
            for o in md.objects:
                why = category(self.chk.scripts, o)
                if why is None and not entered:
                    why = "not enterable in uniform"
                elif why is None and o["index"] not in shown:
                    if o["index"] not in self.period.visible.get(md.id, set()):
                        why = "hidden for the whole uniform period (hide flag %s)" % o.get("flag")
                    else:
                        why = "out of reach in uniform (no tile next to it can be reached)"
                if why is not None:
                    self.rows.append((md.name, o, "skip", why))
                elif reacts(self.chk.scripts, o["script"]):
                    self.rows.append((md.name, o, "yes", ""))
                else:
                    self.rows.append((md.name, o, "no", ""))

    def optional_talks(self):
        """people a side talk brings out (LANETTE after the FALLARBOR chat, the WHITE HERB florist after the flower
        shop): the flags the scripts of the people met in uniform write are unknown, not the story's value"""
        chk, per = self.chk, self.period
        story = set()  # flags the story's scenes write: the simulation already follows them
        for leg in json.load(open(cp.TABLE))["legs"]:
            for label in cp.scene_labels(leg):
                for op, args in walk_cmds(chk.scripts, label, limit=4000):
                    if op in ("setflag", "clearflag") and args:
                        story.add(chk.sim.fkey(args[0]))
        optional = set()
        for m in per.maps:
            md = chk.world.maps[m]
            for o in md.objects:
                if o["index"] in per.shown.get(m, ()) and category(chk.scripts, o) is None:
                    for op, args in walk_cmds(chk.scripts, o["script"], limit=600):
                        if op in ("setflag", "clearflag") and args and chk.sim.fkey(args[0]) not in story:
                            optional.add(chk.sim.fkey(args[0]))
        for m in per.maps:
            md = chk.world.maps[m]
            hidden = [o for o in md.objects if o["index"] not in per.visible.get(m, ())
                      and category(chk.scripts, o) is None]
            if not hidden:
                continue
            for st in per.states:
                st2 = st.copy()
                for k in optional:
                    st2.flags[k] = cp.UNK
                v = cp.MapView(chk, md, st2)
                for o in v.objects:
                    if any(o["index"] == h["index"] for h in hidden):
                        per.visible.setdefault(m, set()).add(o["index"])
                        if talkable(o, per.tiles.get(m, set()), v):
                            per.shown.setdefault(m, set()).add(o["index"])

    def counted(self):
        return [r for r in self.rows if r[2] != "skip"]

    def first_line(self, label):
        """the first text the script shows (for --missing)"""
        for op, args in walk_cmds(self.chk.scripts, label, limit=200):
            if op in ("msgbox", "message") and args and args[0] in self.texts:
                return self.texts[args[0]]
        return ""


def text_index():
    out = {}
    files = glob.glob(os.path.join(ROOT, "data/maps/*/scripts.inc")) + glob.glob(
        os.path.join(ROOT, "data/scripts/**/*.inc"), recursive=True) + glob.glob(os.path.join(ROOT, "data/text/*.inc"))
    lab = re.compile(r'^(\w+)::?[^\n]*\n((?:[ \t]*\.string "(?:[^"\\]|\\.)*"[^\n]*\n)+)', re.M)
    for path in files:
        for name, body in lab.findall(open(path, errors="replace").read()):
            out[name] = " / ".join(gsd.pretty("".join(re.findall(r'\.string "((?:[^"\\]|\\.)*)"', body))))
    return out


# ---------------------------------------------------------------------------------------------------------------
# --doc
# ---------------------------------------------------------------------------------------------------------------

AREA_TITLES = {}  # file stem -> section title (default: from the file's first comment line)
# the generated sections in story order (files not listed follow, by name)
AREA_ORDER = ["draconid_village", "littleroot", "oldale", "petalburg", "routes_south", "rustboro", "dewford", "sea",
              "slateport", "mauville", "routes_central", "verdanturf", "fallarbor", "lavaridge", "routes_north",
              "fortree", "lilycove", "lilycove_contest", "mossdeep", "sootopolis", "pacifidlog", "ever_grande"]


def doc_sections(already):
    """Markdown for the reputation scripts the hand-written tables don't list"""
    out = []
    total = 0
    paths = sorted(glob.glob(os.path.join(REP_DIR, "*.pory")))
    rank = {stem: i for i, stem in enumerate(AREA_ORDER)}
    paths.sort(key=lambda p: (rank.get(os.path.basename(p)[:-5], len(rank)), p))
    for path in paths:
        src = open(path).read()
        title = AREA_TITLES.get(os.path.basename(path)[:-5])
        if title is None:
            m = re.match(r"//.*?–\s*(.+?)\s*(?:\(|$)", src.splitlines()[0])
            title = m.group(1).rstrip(".") if m else os.path.basename(path)
        texts = {}
        for kind, name, body in gsd.blocks(src):
            if kind == "text":
                f = gsd.FORMAT.search(body)
                texts[name] = gsd.join_strings(f.group(1)) if f else gsd.join_strings(body)
        rows = []
        for m in re.finditer(r"((?:^//[^\n]*\n)*)^script\s+(\w+)\s*\{", src, re.M):
            name = m.group(2)
            if name in already or "_DraconidRep" not in name or any(name.endswith(a) for a in already if a.startswith("_")):
                continue
            body = next(b for k, n, b in gsd.blocks(src[m.start(2) - 7:]) if n == name)
            comment = " ".join(l[2:].strip() for l in m.group(1).splitlines())
            who, vanilla = comment, ""
            vm = re.search(r'\(vanilla[^:]*:\s*(.*)\)\s*$', comment)
            if vm:
                who, vanilla = comment[:vm.start()].strip(), vm.group(1).strip()
            uni, rev = [], []
            for t in re.findall(r"msgbox\(\s*(\w+)|message\(\s*(\w+)", body):
                t = t[0] or t[1]
                if t not in texts:
                    continue
                tm = re.search(r"(Uniform|Revealed)(\w*)$", t)
                if not tm:
                    continue
                boxes = " / ".join(gsd.pretty(texts[t]))
                branch = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", tm.group(2)).strip()
                cell = ("**%s:** " % branch if branch else "") + boxes
                (uni if tm.group(1) == "Uniform" else rev).append(cell)
            if "MSGBOX_DEFAULT" in body and "RepTurnAway" not in body:
                # the line is said first, then the vanilla script runs (its gift, service or story line)
                uni = [c + " → *vanilla script*" for c in uni]
                rev = [c + " → *vanilla script*" for c in rev]
            mapname = map_of(name)
            rows.append("| %s | %s | `%s` | %s | %s | %s |" % (mapname, who, name, vanilla or "–",
                                                              "<br>".join(uni) or "vanilla",
                                                              "<br>".join(rev) or "vanilla"))
        if rows:
            total += len(rows)
            out += ["### %s" % title, "",
                    "| Map | NPC | Script | Pre-uniform (vanilla) | Uniform | Revealed |", "|---|---|---|---|---|---|"]
            out += rows + [""]
    return out, total


def map_of(label):
    names = [os.path.basename(os.path.dirname(p)) for p in glob.glob(os.path.join(ROOT, "data/maps/*/map.json"))]
    best = ""
    for n in names:
        if label.startswith(n + "_") and len(n) > len(best):
            best = n
    return best or label.split("_EventScript")[0]


def write_doc(cov):
    text = open(DOC).read()
    head = text.split(DOC_BEGIN)[0]
    tail = text.split(DOC_END, 1)[1] if DOC_END in text else ""
    already = set(re.findall(r"`(\w+_DraconidRep\w+)`", head + tail))
    already |= set(re.findall(r"`…(_\w*DraconidRep\w+)`", head + tail))  # "…_DraconidRepX": the map prefix left out
    sections, total = doc_sections(already)
    counted = cov.counted()
    yes = sum(1 for r in counted if r[2] == "yes")
    body = [DOC_BEGIN, "", "## More townsfolk (round 2, D-360)", "",
            "Written by `check_reputation.py --doc` from the scripts (%d NPCs). Coverage now: **%d of %d** people the "
            "player can meet in uniform react to it (`python3 tools/hack/check_reputation.py`)." % (total, yes, len(counted)),
            ""] + sections + [DOC_END]
    open(DOC, "w").write(head + "\n".join(body) + (tail or "\n"))
    print("wrote %s: %d generated rows" % (os.path.relpath(DOC, ROOT), total))


# ---------------------------------------------------------------------------------------------------------------

def spot(o):
    return "(%d, %d)" % (o["x"], o["y"])


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--missing", action="store_true", help="list the NPCs without a uniform branch")
    ap.add_argument("--skipped", action="store_true", help="what isn't counted, by reason")
    ap.add_argument("--map", help="every object on the maps whose name contains this")
    ap.add_argument("--maps", action="store_true", help="the maps that can / can't be entered in uniform")
    ap.add_argument("--doc", action="store_true", help="rewrite the generated part of docs/reputation_dialogue.md")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()
    t0 = time.time()
    cov = Coverage(args.verbose)
    world = cov.chk.world
    if args.maps:
        print("enterable in uniform (%d): %s" % (len(cov.period.maps), " ".join(sorted(world.pretty(m) for m in cov.period.maps))))
        rest = sorted(md.name for md in world.maps.values() if md.id not in cov.period.maps)
        print("\nnot enterable in uniform (%d): %s" % (len(rest), " ".join(rest)))
        return 0
    if args.doc:
        write_doc(cov)
        return 0
    if args.map:
        for name, o, verdict, why in cov.rows:
            if args.map.lower() in name.lower():
                print("%-36s %-3s %-9s %-26s %-60s %s" % (name, o["index"], spot(o), o["graphics_id"][14:], o.get("script"),
                                                       {"yes": "REACTS", "no": "MISSING"}.get(verdict, "skip: " + why)))
        return 0
    if args.skipped:
        by = {}
        for name, o, verdict, why in cov.rows:
            if verdict == "skip" and why != "no script":
                by.setdefault(re.sub(r" \(hide flag .*\)", "", why), []).append((name, o))
        for why, items in sorted(by.items(), key=lambda kv: -len(kv[1])):
            print("%5d  %s" % (len(items), why))
            if args.verbose:
                for name, o in items:
                    print("         %-36s %-9s %-24s %s" % (name, spot(o), o["graphics_id"][14:], o.get("script")))
        return 0
    per = {}
    for name, o, verdict, why in cov.counted():
        per.setdefault(name, [0, 0])
        per[name][1] += 1
        if verdict == "yes":
            per[name][0] += 1
    if args.missing:
        n = 0
        for name, o, verdict, why in cov.rows:
            if verdict == "no":
                n += 1
                line = cov.first_line(o["script"])
                print("%-36s %-9s %-22s %s\n      %s" % (name, spot(o), o["graphics_id"][14:], o["script"],
                                                       line[:150] + ("…" if len(line) > 150 else "")))
        print("%d NPC(s) without a uniform branch" % n)
        return 1 if n else 0
    for name in sorted(per):
        y, t = per[name]
        print("%-40s %3d / %-3d %s" % (name, y, t, "" if y == t else "(%d missing)" % (t - y)))
    yes = sum(v[0] for v in per.values())
    tot = sum(v[1] for v in per.values())
    print("\n%d of %d people the player can meet in uniform react to it (%.0f%%), %d missing; %d maps enterable in "
          "uniform (%d legs of the story), %.0fs" % (yes, tot, 100.0 * yes / max(tot, 1), tot - yes, len(cov.period.maps),
                                                   len(cov.period.legs), time.time() - t0))
    return 1 if yes < tot else 0


if __name__ == "__main__":
    sys.exit(main())
