#!/usr/bin/env python3
"""
gen_outfit_code.py - (re)generate the C data for the player outfit sprite sets.

Every set in SETS gets nine object-event graphics (normal walk+run, Mach Bike, Acro Bike,
surfing, field move, fishing, underwater, watering, decorating), a palette and a water
reflection palette. The code is written between marker comments

    // BEGIN DRACONID PLAYER OUTFITS (generated by tools/hack/art/player/gen_outfit_code.py)
    // END DRACONID PLAYER OUTFITS

in the files listed in TARGETS; everything outside the markers is left alone. NPCS (the Draconid
villagers and Aster, standard 9-frame sheets) are generated the same way. Run it after adding a
set or NPC, then `make`.

  python3 tools/hack/art/player/gen_outfit_code.py
"""

import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
BEGIN = "// BEGIN DRACONID PLAYER OUTFITS (generated by tools/hack/art/player/gen_outfit_code.py)"
END = "// END DRACONID PLAYER OUTFITS"

# (CamelName, CONST_NAME, graphics dir / palette file stem, first palette tag)
SETS = [
    ("DraconidM", "DRACONID_M", "draconid_m", 0x1140),
    ("DraconidF", "DRACONID_F", "draconid_f", 0x1142),
    ("MagmaM", "MAGMA_M", "magma_m", 0x1144),
    ("MagmaF", "MAGMA_F", "magma_f", 0x1146),
]

# Draconid NPCs (standard 9-frame 16x32 sheets): (CamelName, CONST_NAME, png, palette stem)
NPCS = [
    ("DraconidElder", "DRACONID_ELDER", "draconid/elder.png", "draconid_npc"),
    ("DraconidOldWoman", "DRACONID_OLD_WOMAN", "draconid/old_woman.png", "draconid_npc"),
    ("DraconidMan", "DRACONID_MAN", "draconid/man.png", "draconid_npc"),
    ("DraconidWoman", "DRACONID_WOMAN", "draconid/woman.png", "draconid_npc"),
    ("DraconidBoy", "DRACONID_BOY", "draconid/boy.png", "draconid_npc"),
    ("DraconidGuard", "DRACONID_GUARD", "draconid/guard.png", "draconid_npc"),
    ("Aster", "ASTER", "draconid/aster.png", "aster"),
    # round 1: Nerine undercover in Team Aqua and in her own clothes, Magma admin Courtney
    # (sheets from tools/hack/art/recipes/{nerine_aqua,nerine,courtney}.json)
    ("NerineAqua", "NERINE_AQUA", "draconid/nerine_aqua.png", "nerine_aqua"),
    ("Nerine", "NERINE", "draconid/nerine.png", "nerine"),
    ("Courtney", "COURTNEY", "draconid/courtney.png", "courtney"),
    # Act 7: Zinnia, the Lorekeeper at the Sky Pillar. TODO(art): placeholder sheet + palette (the Hex Maniac's,
    # npc_4.pal); the real Zinnia replaces draconid/zinnia.png and palettes/zinnia{,_reflection}.pal
    ("Zinnia", "ZINNIA", "draconid/zinnia.png", "zinnia"),
]
# palette stem -> (CamelName, tag CONST, tag value)
NPC_PALETTES = [("DraconidNpc", "DRACONID_NPC", 0x1148, "draconid_npc"), ("Aster", "ASTER", 0x1149, "aster"),
                ("DraconidEggs", "DRACONID_EGGS", 0x114A, "draconid_eggs"),
                ("NerineAqua", "NERINE_AQUA", 0x114B, "nerine_aqua"), ("Nerine", "NERINE", 0x114C, "nerine"),
                ("Courtney", "COURTNEY", 0x114D, "courtney"), ("Zinnia", "ZINNIA", 0x114E, "zinnia")]
# single-frame inanimate 16x32 objects: (CamelName, CONST_NAME, png under pics/, palette stem)
OBJECTS = [
    ("DraconidEggDeino", "DRACONID_EGG_DEINO", "misc/draconid_egg_deino.png", "draconid_eggs"),
    ("DraconidEggDreepy", "DRACONID_EGG_DREEPY", "misc/draconid_egg_dreepy.png", "draconid_eggs"),
    ("DraconidEggJangmoO", "DRACONID_EGG_JANGMO_O", "misc/draconid_egg_jangmo_o.png", "draconid_eggs"),
]

STATES = ["NORMAL", "MACH_BIKE", "ACRO_BIKE", "SURFING", "FIELD_MOVE", "FISHING", "UNDERWATER", "WATERING",
          "DECORATING"]
STATE_CAMEL = {"NORMAL": "Normal", "MACH_BIKE": "MachBike", "ACRO_BIKE": "AcroBike", "SURFING": "Surfing",
               "FIELD_MOVE": "FieldMove", "FISHING": "Fishing", "UNDERWATER": "Underwater",
               "WATERING": "Watering", "DECORATING": "Decorating"}

# pic arrays: name suffix, png, metatile width/height (in tiles)
PICS = [("Walking", "walking.png", 2, 4), ("Running", "running.png", 2, 4), ("MachBike", "bike.png", 4, 4),
        ("AcroBike", "acro_bike.png", 4, 4), ("Surfing", "surfing.png", 2, 4), ("FieldMove", "field_move.png", 2, 4),
        ("Fishing", "fishing.png", 4, 4), ("Underwater", "underwater.png", 4, 4), ("Watering", "watering.png", 4, 4),
        ("Decorating", "decorating.png", 2, 4)]

# graphics info per state: size, width, height, anims, tracks, palette ('own', 'underwater'), reflection, slot, inanimate
INFO = {
    "NORMAL":     (512, 16, 32, "sAnimTable_BrendanMayNormal", "TRACKS_FOOT", "own", True, "PALSLOT_PLAYER", False),
    "MACH_BIKE":  (512, 32, 32, "sAnimTable_Standard", "TRACKS_BIKE_TIRE", "own", True, "PALSLOT_PLAYER", False),
    "ACRO_BIKE":  (512, 32, 32, "sAnimTable_AcroBike", "TRACKS_BIKE_TIRE", "own", True, "PALSLOT_PLAYER", False),
    "SURFING":    (256, 16, 32, "sAnimTable_Surfing", "TRACKS_FOOT", "own", False, "PALSLOT_PLAYER", False),
    "FIELD_MOVE": (256, 16, 32, "sAnimTable_FieldMove", "TRACKS_FOOT", "own", True, "PALSLOT_PLAYER", False),
    "FISHING":    (512, 32, 32, "sAnimTable_Fishing", "TRACKS_FOOT", "own", True, "PALSLOT_PLAYER", False),
    "UNDERWATER": (512, 32, 32, "sAnimTable_Standard", "TRACKS_FOOT", "underwater", False, "PALSLOT_PLAYER", False),
    "WATERING":   (512, 32, 32, "sAnimTable_Standard", "TRACKS_FOOT", "own", True, "PALSLOT_PLAYER", False),
    "DECORATING": (256, 16, 32, "sAnimTable_Inanimate", "TRACKS_FOOT", "own", True, "PALSLOT_NPC_SPECIAL", True),
}


def gfx_const(const, state):
    return "OBJ_EVENT_GFX_%s_%s" % (const, state)


def gen_enum():
    lines = []
    for _, const, _, _ in SETS:
        lines += ["    %s," % gfx_const(const, s) for s in STATES]
    lines += ["    OBJ_EVENT_GFX_%s," % const for _, const, _, _ in NPCS + OBJECTS]
    return lines


def gen_pal_tags():
    lines = []
    for _, const, _, tag in SETS:
        lines.append("#define OBJ_EVENT_PAL_TAG_%-32s 0x%04X" % (const, tag))
        lines.append("#define OBJ_EVENT_PAL_TAG_%-32s 0x%04X" % (const + "_REFLECTION", tag + 1))
    for _, const, tag, _ in NPC_PALETTES:
        lines.append("#define OBJ_EVENT_PAL_TAG_%-32s 0x%04X" % (const, tag))
    return lines


def gen_graphics():
    lines = []
    for camel, _, stem, _ in SETS:
        for suffix, png, mw, mh in PICS:
            lines.append('const u32 gObjectEventPic_%s%s[] = INCGFX_U32("graphics/object_events/pics/people/%s/%s", '
                         '".4bpp", "-mwidth %d -mheight %d");' % (camel, suffix, stem, png, mw, mh))
        lines.append('const u16 gObjectEventPal_%s[] = INCGFX_U16("graphics/object_events/palettes/%s.pal", ".gbapal");'
                     % (camel, stem))
        lines.append('const u16 gObjectEventPal_%sReflection[] = INCGFX_U16("graphics/object_events/palettes/%s_reflection.pal", ".gbapal");'
                     % (camel, stem))
    for camel, _, png, _ in NPCS:
        lines.append('const u32 gObjectEventPic_%s[] = INCGFX_U32("graphics/object_events/pics/people/%s", ".4bpp", "-mwidth 2 -mheight 4");'
                     % (camel, png))
    for camel, _, png, _ in OBJECTS:
        lines.append('const u32 gObjectEventPic_%s[] = INCGFX_U32("graphics/object_events/pics/%s", ".4bpp");' % (camel, png))
    for camel, _, _, stem in NPC_PALETTES:
        lines.append('const u16 gObjectEventPal_%s[] = INCGFX_U16("graphics/object_events/palettes/%s.pal", ".gbapal");' % (camel, stem))
    return lines


def frames(arr, w, h, idx):
    return ["    overworld_frame(%s, %d, %d, %d)," % (arr, w, h, i) for i in idx]


def gen_pic_tables():
    lines = []
    for camel, _, _, _ in SETS:
        p = "gObjectEventPic_" + camel
        lines.append("static const struct SpriteFrameImage sPicTable_%sNormal[] = {" % camel)
        lines += frames(p + "Walking", 2, 4, range(9)) + frames(p + "Running", 2, 4, range(9))
        lines.append("};")
        for suffix, w in (("MachBike", 4), ("AcroBike", 4), ("FieldMove", 2), ("Fishing", 4)):
            lines += ["", "static const struct SpriteFrameImage sPicTable_%s%s[] = {" % (camel, suffix),
                      "    overworld_ascending_frames(%s%s, %d, 4)," % (p, suffix, w), "};"]
        lines += ["", "static const struct SpriteFrameImage sPicTable_%sSurfing[] = {" % camel]
        lines += frames(p + "Surfing", 2, 4, [0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 1, 2]) + ["};"]
        lines += ["", "static const struct SpriteFrameImage sPicTable_%sUnderwater[] = {" % camel]
        lines += frames(p + "Underwater", 4, 4, [0, 1, 2, 0, 0, 1, 1, 2, 2]) + ["};"]
        lines += ["", "static const struct SpriteFrameImage sPicTable_%sWatering[] = {" % camel]
        lines += frames(p + "Watering", 4, 4, [0, 2, 4, 1, 1, 3, 3, 5, 5]) + ["};"]
        lines += ["", "static const struct SpriteFrameImage sPicTable_%sDecorating[] = {" % camel,
                  "    obj_frame_tiles(%sDecorating)," % p, "};", ""]
    for camel, _, _, _ in NPCS:
        lines += ["static const struct SpriteFrameImage sPicTable_%s[] = {" % camel,
                  "    overworld_ascending_frames(gObjectEventPic_%s, 2, 4)," % camel, "};", ""]
    for camel, _, _, _ in OBJECTS:
        lines += ["static const struct SpriteFrameImage sPicTable_%s[] = {" % camel,
                  "    obj_frame_tiles(gObjectEventPic_%s)," % camel, "};", ""]
    return lines


def gen_infos():
    lines = []
    for camel, const, _, _ in SETS:
        for s in STATES:
            size, w, h, anims, tracks, pal, refl, slot, inanimate = INFO[s]
            pal_tag = "OBJ_EVENT_PAL_TAG_PLAYER_UNDERWATER" if pal == "underwater" else "OBJ_EVENT_PAL_TAG_" + const
            lines += [
                "const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_%s%s = {" % (camel, STATE_CAMEL[s]),
                "    .tileTag = TAG_NONE,",
                "    .paletteTag = %s," % pal_tag,
                "    .reflectionPaletteTag = %s," % ("OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION" if refl else "OBJ_EVENT_PAL_TAG_NONE"),
                "    .size = %d," % size,
                "    .width = %d," % w,
                "    .height = %d," % h,
                "    .paletteSlot = %s," % slot,
                "    .shadowSize = SHADOW_SIZE_M,",
                "    .inanimate = %s," % ("TRUE" if inanimate else "FALSE"),
                "    .compressed = FALSE,",
                "    .tracks = %s," % tracks,
                "    .oam = &gObjectEventBaseOam_%dx%d," % (w, h),
                "    .subspriteTables = sOamTables_%dx%d," % (w, h),
                "    .anims = %s," % anims,
                "    .images = sPicTable_%s%s," % (camel, STATE_CAMEL[s]),
                "    .affineAnims = gDummySpriteAffineAnimTable,",
                "};",
                "",
            ]
    return lines


def gen_npc_infos():
    lines = []
    tag_of = {stem: const for _, const, _, stem in NPC_PALETTES}
    for camel, _, _, stem in OBJECTS:
        lines += [
            "const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_%s = {" % camel,
            "    .tileTag = TAG_NONE,",
            "    .paletteTag = OBJ_EVENT_PAL_TAG_%s," % tag_of[stem],
            "    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,",
            "    .size = 256,",
            "    .width = 16,",
            "    .height = 32,",
            "    .paletteSlot = PALSLOT_NPC_1,",
            "    .shadowSize = SHADOW_SIZE_S,",
            "    .inanimate = TRUE,",
            "    .compressed = FALSE,",
            "    .tracks = TRACKS_NONE,",
            "    .oam = &gObjectEventBaseOam_16x32,",
            "    .subspriteTables = sOamTables_16x32,",
            "    .anims = sAnimTable_Inanimate,",
            "    .images = sPicTable_%s," % camel,
            "};",
            "",
        ]
    for camel, _, _, stem in NPCS:
        lines += [
            "const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_%s = {" % camel,
            "    .tileTag = TAG_NONE,",
            "    .paletteTag = OBJ_EVENT_PAL_TAG_%s," % tag_of[stem],
            "    .reflectionPaletteTag = OBJ_EVENT_PAL_TAG_NONE,",
            "    .size = 256,",
            "    .width = 16,",
            "    .height = 32,",
            "    .paletteSlot = PALSLOT_NPC_1,",
            "    .shadowSize = SHADOW_SIZE_M,",
            "    .inanimate = FALSE,",
            "    .compressed = FALSE,",
            "    .tracks = TRACKS_FOOT,",
            "    .oam = &gObjectEventBaseOam_16x32,",
            "    .subspriteTables = sOamTables_16x32,",
            "    .anims = sAnimTable_Standard,",
            "    .images = sPicTable_%s," % camel,
            "};",
            "",
        ]
    return lines


def gen_pointers():
    lines = []
    for camel, const, _, _ in SETS:
        lines += ["    [%s] = &gObjectEventGraphicsInfo_%s%s," % (gfx_const(const, s), camel, STATE_CAMEL[s])
                  for s in STATES]
    lines += ["    [OBJ_EVENT_GFX_%s] = &gObjectEventGraphicsInfo_%s," % (const, camel) for camel, const, _, _ in NPCS + OBJECTS]
    return lines


def gen_externs():
    return ["extern const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_%s%s;" % (camel, STATE_CAMEL[s])
            for camel, _, _, _ in SETS for s in STATES] + \
           ["extern const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_%s;" % camel for camel, _, _, _ in NPCS + OBJECTS]


def gen_palettes():
    lines = []
    for camel, const, _, _ in SETS:
        lines.append("    {gObjectEventPal_%s, OBJ_EVENT_PAL_TAG_%s}," % (camel, const))
        lines.append("    {gObjectEventPal_%sReflection, OBJ_EVENT_PAL_TAG_%s_REFLECTION}," % (camel, const))
    for camel, const, _, _ in NPC_PALETTES:
        lines.append("    {gObjectEventPal_%s, OBJ_EVENT_PAL_TAG_%s}," % (camel, const))
    return lines


def gen_reflection_tags():
    lines = []
    for camel, const, _, _ in SETS:
        lines.append("static const u16 sReflectionPaletteTags_%s[] = {" % camel)
        lines += ["    OBJ_EVENT_PAL_TAG_%s_REFLECTION," % const] * 4
        lines.append("};")
    return lines


def gen_reflection_sets():
    return ["    {OBJ_EVENT_PAL_TAG_%s, sReflectionPaletteTags_%s}," % (const, camel) for camel, const, _, _ in SETS]


TARGETS = [
    # (file, region index, generator); region index counts marker pairs in file order
    ("include/constants/event_objects.h", 0, gen_enum),
    ("include/constants/event_objects.h", 1, gen_pal_tags),
    ("src/data/object_events/object_event_graphics.h", 0, gen_graphics),
    ("src/data/object_events/object_event_pic_tables.h", 0, gen_pic_tables),
    ("src/data/object_events/object_event_graphics_info.h", 0, lambda: gen_infos() + gen_npc_infos()),
    ("src/data/object_events/object_event_graphics_info_pointers.h", 0, gen_externs),
    ("src/data/object_events/object_event_graphics_info_pointers.h", 1, gen_pointers),
    ("src/event_object_movement.c", 0, gen_palettes),
    ("src/event_object_movement.c", 1, gen_reflection_tags),
    ("src/event_object_movement.c", 2, gen_reflection_sets),
]


def replace_region(text, index, body):
    """Replace the lines between the index-th BEGIN/END marker pair (keeping the markers)."""
    lines = text.split("\n")
    begins = [i for i, l in enumerate(lines) if l.strip() == BEGIN]
    if index >= len(begins):
        raise SystemExit("marker pair %d not found" % index)
    b = begins[index]
    e = next(i for i in range(b + 1, len(lines)) if lines[i].strip() == END)
    return "\n".join(lines[:b + 1] + body + lines[e:])


def main():
    by_file = {}
    for path, idx, gen in TARGETS:
        by_file.setdefault(path, []).append((idx, gen))
    for path, regions in by_file.items():
        full = os.path.join(ROOT, path)
        text = open(full).read()
        for idx, gen in regions:
            text = replace_region(text, idx, gen())
        open(full, "w").write(text)
        print("updated", path)


if __name__ == "__main__":
    main()
