LilycoveCity_ContestHall_EventScript_DraconidRepBoy1::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBoy1_2
	goto LilycoveCity_ContestHall_EventScript_Boy1
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBoy1_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBoy1Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBoy2::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBoy2_2
	goto LilycoveCity_ContestHall_EventScript_Boy2
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBoy2_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBoy2Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepGirl::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepGirl_2
	goto LilycoveCity_ContestHall_EventScript_Girl
	return

LilycoveCity_ContestHall_EventScript_DraconidRepGirl_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepGirlUniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestMC::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestMC_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestMC
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestMC_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestMCUniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestJudge::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestJudge_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestJudge
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestJudge_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestJudgeUniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant1::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant1_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestant1
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant1_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestant1Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant2::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant2_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestant2
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant2_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestant2Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant3::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant3_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestant3
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant3_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestant3Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant4::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant4_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestant4
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestant4_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestant4Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience1::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience1_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestAudience1
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience1_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestAudience1Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience4::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience4_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestAudience4
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience4_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestAudience4Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience2::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience2_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestAudience2
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience2_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestAudience2Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestMC::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestMC_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestMC
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestMC_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestMCUniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestJudge::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestJudge_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestJudge
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestJudge_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestJudgeUniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant1::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant1_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestant1
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant1_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestant1Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant2::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant2_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestant2
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant2_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestant2Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant3::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant3_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestant3
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant3_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestant3Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant4::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant4_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestant4
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestant4_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestant4Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience1::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience1_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestAudience1
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience1_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestAudience1Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience3::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience3_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestAudience3
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience3_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestAudience3Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience2::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience2_2
	goto LilycoveCity_ContestHall_EventScript_BeautyContestAudience2
	return

LilycoveCity_ContestHall_EventScript_DraconidRepBeautyContestAudience2_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepBeautyContestAudience2Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience3::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience3_2
	goto LilycoveCity_ContestHall_EventScript_SmartContestAudience3
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSmartContestAudience3_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSmartContestAudience3Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestMC::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestMC_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestMC
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestMC_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestMCUniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestJudge::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestJudge_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestJudge
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestJudge_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestJudgeUniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant1::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant1_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestant1
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant1_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestant1Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant2::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant2_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestant2
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant2_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestant2Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant3::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant3_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestant3
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant3_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestant3Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant4::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant4_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestant4
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestant4_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestant4Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience1::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience1_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestAudience1
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience1_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestAudience1Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience3::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience3_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestAudience3
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience3_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestAudience3Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience2::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience2_2
	goto LilycoveCity_ContestHall_EventScript_CuteContestAudience2
	return

LilycoveCity_ContestHall_EventScript_DraconidRepCuteContestAudience2_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepCuteContestAudience2Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_EventScript_DraconidRepSailor::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestHall_EventScript_DraconidRepSailor_2
	goto LilycoveCity_ContestHall_EventScript_Sailor
	return

LilycoveCity_ContestHall_EventScript_DraconidRepSailor_2:
	msgbox LilycoveCity_ContestHall_Text_DraconidRepSailorUniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepContestReceptionist::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepContestReceptionist_2
LilycoveCity_ContestLobby_EventScript_DraconidRepContestReceptionist_1:
	goto LilycoveCity_ContestLobby_EventScript_ContestReceptionist
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepContestReceptionist_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepContestReceptionistUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepContestReceptionist_1


LilycoveCity_ContestLobby_EventScript_DraconidRepLinkContestReceptionist::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepLinkContestReceptionist_2
LilycoveCity_ContestLobby_EventScript_DraconidRepLinkContestReceptionist_1:
	goto LilycoveCity_ContestLobby_EventScript_LinkContestReceptionist
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepLinkContestReceptionist_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepLinkContestReceptionistUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepLinkContestReceptionist_1


LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Man::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Man_2
LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Man_1:
	goto BerryBlender_EventScript_Blender2Man
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Man_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlender2ManUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Man_1


LilycoveCity_ContestLobby_EventScript_DraconidRepBlackBelt::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepBlackBelt_2
	goto LilycoveCity_ContestLobby_EventScript_BlackBelt
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlackBelt_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlackBeltUniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepGirl::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepGirl_2
	goto LilycoveCity_ContestLobby_EventScript_Girl
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepGirl_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepGirlUniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepArtist::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepArtist_2
	goto LilycoveCity_ContestLobby_EventScript_Artist
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepArtist_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepArtistUniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Boy::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Boy_2
LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Boy_1:
	goto LilycoveCity_ContestLobby_EventScript_Blender3Boy
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Boy_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlender3BoyUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Boy_1


LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Twin::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Twin_2
LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Twin_1:
	goto BerryBlender_EventScript_Blender2Twin
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Twin_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlender2TwinUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepBlender2Twin_1


LilycoveCity_ContestLobby_EventScript_DraconidRepFisherman::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepFisherman_2
	goto LilycoveCity_ContestLobby_EventScript_Fisherman
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepFisherman_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepFishermanUniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepFatMan::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepFatMan_2
	goto LilycoveCity_ContestLobby_EventScript_FatMan
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepFatMan_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepFatManUniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepNinjaBoy::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepNinjaBoy_2
	goto LilycoveCity_ContestLobby_EventScript_NinjaBoy
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepNinjaBoy_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepNinjaBoyUniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3PokefanF::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3PokefanF_2
LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3PokefanF_1:
	goto BerryBlender_EventScript_Blender3PokefanF
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3PokefanF_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlender3PokefanFUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3PokefanF_1


LilycoveCity_ContestLobby_EventScript_DraconidRepBlender1ExpertM::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepBlender1ExpertM_2
LilycoveCity_ContestLobby_EventScript_DraconidRepBlender1ExpertM_1:
	goto BerryBlender_EventScript_Blender1ExpertM
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlender1ExpertM_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlender1ExpertMUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepBlender1ExpertM_1


LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Girl::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Girl_2
LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Girl_1:
	goto LilycoveCity_ContestLobby_EventScript_Blender3Girl
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Girl_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlender3GirlUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepBlender3Girl_1


LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker2::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker2_2
	goto LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker2
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker2_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker2Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker3::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker3_2
	goto LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker3
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker3_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker3Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker4::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker4_2
	goto LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker4
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker4_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker4Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker5::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker5_2
	goto LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker5
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker5_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker5Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker6::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker6_2
	goto LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker6
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker6_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker6Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker1::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker1_2
	goto LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker1
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMasterOnlooker1_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker1Uniform, MSGBOX_NPC
	return


LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMaster::
	compare VAR_DRACONID_REPUTATION, REPUTATION_UNIFORM
	goto_if_eq LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMaster_2
LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMaster_1:
	goto LilycoveCity_ContestLobby_EventScript_BlendMaster
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMaster_2:
	lock
	faceplayer
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterUniform, MSGBOX_DEFAULT
	goto LilycoveCity_ContestLobby_EventScript_DraconidRepBlendMaster_1


LilycoveCity_ContestLobby_EventScript_DraconidRepLittleGirl::
	switch VAR_DRACONID_REPUTATION
	case REPUTATION_UNIFORM, LilycoveCity_ContestLobby_EventScript_DraconidRepLittleGirl_2
	goto LilycoveCity_ContestLobby_EventScript_LittleGirl
	return

LilycoveCity_ContestLobby_EventScript_DraconidRepLittleGirl_2:
	msgbox LilycoveCity_ContestLobby_Text_DraconidRepLittleGirlUniform, MSGBOX_NPC
	return


LilycoveCity_ContestHall_Text_DraconidRepBoy1Uniform::
	.string "My POKéMON won a BEAUTY CONTEST, and\n"
	.string "now a SMARTNESS one!\p"
	.string "A TEAM MAGMA grunt in the audience?\p"
	.string "My abilities scare even me… But you\n"
	.string "scare me more.$"

LilycoveCity_ContestHall_Text_DraconidRepBoy2Uniform::
	.string "Cool moves go over well in a COOLNESS\n"
	.string "CONTEST.\p"
	.string "Is there a SCARINESS CONTEST? You'd\n"
	.string "win that one in a walk.$"

LilycoveCity_ContestHall_Text_DraconidRepGirlUniform::
	.string "The winner earlier had all kinds of\n"
	.string "{POKEBLOCK}S.\p"
	.string "Do TEAM MAGMA grunts make {POKEBLOCK}S? I\n"
	.string "bet yours taste like ash.$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestMCUniform::
	.string "MC: Okay, SMART POKéMON and their\n"
	.string "TRAINERS…\p"
	.string "Is that a TEAM MAGMA uniform in the\n"
	.string "crowd?\p"
	.string "Ahem! Give it your best showing! Let's\n"
	.string "appeal!$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestJudgeUniform::
	.string "JUDGE: Enjoying the CONTEST? We judge\n"
	.string "POKéMON, not the TRAINERS' clothes.\p"
	.string "…Though I'd score that uniform rather\n"
	.string "low.$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestant1Uniform::
	.string "Ayayayay… I entered a tough POKéMON in\n"
	.string "the SMARTNESS CONTEST.\p"
	.string "And there's TEAM MAGMA watching. Could\n"
	.string "this get any worse?$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestant2Uniform::
	.string "Years of wisdom went into raising this\n"
	.string "smart POKéMON.\p"
	.string "It won't be bested by some young pup's\n"
	.string "POKéMON.\p"
	.string "Least of all a TEAM MAGMA pup's.$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestant3Uniform::
	.string "If my POKéMON pulls a smart move next,\n"
	.string "the crowd will go wild!\p"
	.string "Unless TEAM MAGMA scares them all off\n"
	.string "first.$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestant4Uniform::
	.string "Oh, dear, no! Nobody appreciates my\n"
	.string "ZUBAT's LEECH LIFE!\p"
	.string "You do? …You're TEAM MAGMA. That\n"
	.string "doesn't count.$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestAudience1Uniform::
	.string "Kiyaaah! You're beautiful, Grandpa!\p"
	.string "…Who invited TEAM MAGMA? Shoo, you're\n"
	.string "blocking my view!$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestAudience4Uniform::
	.string "I still love SMARTNESS CONTESTS. That\n"
	.string "intellectual green color…\p"
	.string "So much nicer than TEAM MAGMA red.$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestAudience2Uniform::
	.string "Every TRAINER uses different appeals,\n"
	.string "the way they battle differently.\p"
	.string "What's TEAM MAGMA's style? Burning down\n"
	.string "the stage?$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestMCUniform::
	.string "MC: Are you entering the BEAUTY\n"
	.string "CONTEST, too?\p"
	.string "In that uniform? …Well, good luck!$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestJudgeUniform::
	.string "JUDGE: Every POKéMON here is a model of\n"
	.string "pristine beauty!\p"
	.string "Why, I nearly scored your uniform by\n"
	.string "mistake. Zero points.$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestant1Uniform::
	.string "A POKéMON this beautiful… Everyone's\n"
	.string "eyes will be glued to my beauty.\p"
	.string "Not to the TEAM MAGMA grunt in the\n"
	.string "crowd, I hope.$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestant2Uniform::
	.string "Waaaah! I overdid the grooming and my\n"
	.string "POKéMON's coat went scraggly!\p"
	.string "And now TEAM MAGMA's laughing at me!\n"
	.string "Waaaah!$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestant3Uniform::
	.string "This AURORA BEAM is so dazzling, the\n"
	.string "JUDGE won't see a thing!\p"
	.string "Maybe I'll dazzle that TEAM MAGMA grunt\n"
	.string "into leaving.$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestant4Uniform::
	.string "This pretty POKéMON looks just like me\n"
	.string "when I was younger.\p"
	.string "A TEAM MAGMA grunt just snorted. Did I\n"
	.string "say something funny?$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestAudience1Uniform::
	.string "Winning a BEAUTY CONTEST makes me\n"
	.string "happy. More than usual.\p"
	.string "Seeing TEAM MAGMA here makes me less\n"
	.string "happy than usual.$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestAudience3Uniform::
	.string "You can't win on beauty alone. Grooming\n"
	.string "is the key.\p"
	.string "That uniform could use some grooming,\n"
	.string "TEAM MAGMA.$"

LilycoveCity_ContestHall_Text_DraconidRepBeautyContestAudience2Uniform::
	.string "Wahahahah! Look at all those pretty\n"
	.string "POKéMON! I love this glitz!\p"
	.string "Even TEAM MAGMA came to see the glitz!\n"
	.string "Wahahah! …Wait, really?$"

LilycoveCity_ContestHall_Text_DraconidRepSmartContestAudience3Uniform::
	.string "The POKéMON look smarter than their\n"
	.string "TRAINERS. By a lot.\p"
	.string "Yours, too. Especially yours, TEAM\n"
	.string "MAGMA.$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestMCUniform::
	.string "MC: Uh-oh! Hello! We're in the middle of\n"
	.string "a CONTEST!\p"
	.string "And TEAM MAGMA, too? Please enter at\n"
	.string "the counter like everyone else, okay?$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestJudgeUniform::
	.string "JUDGE: Oh, such charming and cute\n"
	.string "appeals!\p"
	.string "Oh, my goodness! A TEAM MAGMA grunt!\n"
	.string "Not charming at all!$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestant1Uniform::
	.string "Oh, no… My sweet AZURILL got\n"
	.string "distracted.\p"
	.string "It was staring at your red uniform.\n"
	.string "Thanks a lot.$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestant2Uniform::
	.string "My POKéMON never wins battles, but in a\n"
	.string "CONTEST, look out!\p"
	.string "So no battling, TEAM MAGMA. Not here.$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestant3Uniform::
	.string "My POKéMON's PETAL DANCE is a marvel of\n"
	.string "elegance.\p"
	.string "I won't let anyone disturb it.\n"
	.string "Especially not TEAM MAGMA.$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestant4Uniform::
	.string "Everyone's POKéMON are cute, but mine\n"
	.string "would be cuter.\p"
	.string "A TEAM MAGMA POKéMON entering the CUTE\n"
	.string "CONTEST? Unthinkable.$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestAudience1Uniform::
	.string "My child is in this CONTEST.\p"
	.string "Please stay away from my child, TEAM\n"
	.string "MAGMA. And from the stage.$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestAudience3Uniform::
	.string "That girl over there is the cutest of\n"
	.string "the lot.\p"
	.string "What's that? I'm supposed to watch the\n"
	.string "POKéMON? And you're TEAM MAGMA? Huh.$"

LilycoveCity_ContestHall_Text_DraconidRepCuteContestAudience2Uniform::
	.string "All these cute POKéMON make me want my\n"
	.string "own!\p"
	.string "I won't catch any near TEAM MAGMA,\n"
	.string "though. They might get scared.$"

LilycoveCity_ContestHall_Text_DraconidRepSailorUniform::
	.string "Whoa, isn't this place humongous! The\n"
	.string "tension in the air…\p"
	.string "And now TEAM MAGMA's here. More tension\n"
	.string "than ever.$"

LilycoveCity_ContestLobby_Text_DraconidRepContestReceptionistUniform::
	.string "Welcome to the… Oh. A TEAM MAGMA\n"
	.string "member.\p"
	.string "The CONTEST rules say anyone may\n"
	.string "enter. I'll follow them.$"

LilycoveCity_ContestLobby_Text_DraconidRepLinkContestReceptionistUniform::
	.string "Welcome… The link counter is open to all\n"
	.string "TRAINERS. Even TEAM MAGMA.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlender2ManUniform::
	.string "Hey, are you trying to blend with us,\n"
	.string "TEAM MAGMA? Hmph. Okay, fine.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlackBeltUniform::
	.string "Hoo, boy… Master Rank CONTESTS, here I\n"
	.string "come!\p"
	.string "My POKéMON's cuteness will melt even a\n"
	.string "TEAM MAGMA heart. Uheheheh.$"

LilycoveCity_ContestLobby_Text_DraconidRepGirlUniform::
	.string "You can see all kinds of POKéMON here.\n"
	.string "That's why I stroll by daily.\p"
	.string "All kinds of people, too. Even TEAM\n"
	.string "MAGMA, apparently.$"

LilycoveCity_ContestLobby_Text_DraconidRepArtistUniform::
	.string "All these POKéMON just scream to be\n"
	.string "painted!\p"
	.string "You, though, TEAM MAGMA? I'd need a lot\n"
	.string "more red paint.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlender3BoyUniform::
	.string "TEAM MAGMA wants to blend with us? Ugh,\n"
	.string "fine.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlender2TwinUniform::
	.string "You want to make {POKEBLOCK}S, TEAM MAGMA?\n"
	.string "Okay…$"

LilycoveCity_ContestLobby_Text_DraconidRepFishermanUniform::
	.string "Day after day, I lavished care on this\n"
	.string "POKéMON. Today, victory is mine!\p"
	.string "Unless TEAM MAGMA sabotages me. You\n"
	.string "won't, right? Right?$"

LilycoveCity_ContestLobby_Text_DraconidRepFatManUniform::
	.string "The TOUGHNESS CONTEST is extreme, man!\n"
	.string "Those muscular appeals…\p"
	.string "TEAM MAGMA should enter. You guys love\n"
	.string "extreme stuff.$"

LilycoveCity_ContestLobby_Text_DraconidRepNinjaBoyUniform::
	.string "I made {POKEBLOCK}S with my family. They\n"
	.string "turned out great!\p"
	.string "Do TEAM MAGMA grunts make {POKEBLOCK}S\n"
	.string "together? That'd be funny.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlender3PokefanFUniform::
	.string "Oh, dear! A TEAM MAGMA member… Well,\n"
	.string "everyone's welcome at the BLENDER.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlender1ExpertMUniform::
	.string "TEAM MAGMA, at the BERRY BLENDER? My,\n"
	.string "my.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlender3GirlUniform::
	.string "Is TEAM MAGMA going to blend with us?\n"
	.string "So exciting! And so scary!$"

LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker2Uniform::
	.string "Wickedly fast!\p"
	.string "…Hey, no cutting in to watch, TEAM\n"
	.string "MAGMA.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker3Uniform::
	.string "What an expert!\p"
	.string "You'd never blend that fast, TEAM\n"
	.string "MAGMA. You're too busy plotting.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker4Uniform::
	.string "When I blended with the MASTER, we made\n"
	.string "amazing {POKEBLOCK}S!\p"
	.string "Are you going to blend with him, TEAM\n"
	.string "MAGMA? He blends with anyone…$"

LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker5Uniform::
	.string "Eyes that track the arrow with\n"
	.string "machinelike intensity…\p"
	.string "Not the eyes of a TEAM MAGMA grunt.\n"
	.string "Those are shifty.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker6Uniform::
	.string "The BLEND MASTER trains deep in the\n"
	.string "mountains.\p"
	.string "Clean mountain air must be good for\n"
	.string "blending.\p"
	.string "TEAM MAGMA should try it instead of\n"
	.string "volcano smoke.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterOnlooker1Uniform::
	.string "Whoa! Awesome!\p"
	.string "Huh? A TEAM MAGMA grunt? Whoa… Less\n"
	.string "awesome.$"

LilycoveCity_ContestLobby_Text_DraconidRepBlendMasterUniform::
	.string "BLEND MASTER: Hmm! A TEAM MAGMA grunt,\n"
	.string "come to test my mastery?$"

LilycoveCity_ContestLobby_Text_DraconidRepLittleGirlUniform::
	.string "Yippee! The lady at the counter gave me\n"
	.string "a case for {POKEBLOCK}S!\p"
	.string "You can't have it, TEAM MAGMA. It's mine!$"
