# gen49_plan.py - the Gen 4-9 swaps of the second pass (round 1 follow-up, feedback 1.40, D-240 - D-242),
# applied by gen49.py (docs/hack_trainers.md, "Gen 4-9 swaps"). D-195's first pass is already in
# src/data/trainers.party (its swaps are recorded in gen49_swaps.json); this plan adds to it.
#
# PLAN[first battle id without TRAINER_] = [(old, new line, cond), ...], applied to the first battle and every
# rematch tier (segments.json):
#   old   a species of the family that makes way: its first member in the block that is neither the ace (last) nor
#         a Gen 4-9 Pokemon; "Geodude#2" = the second one, "A|B" = the first family found, "~X" may replace an
#         earlier Gen 4-9 swap, "X!" may take the ace
#   new   the last species of the new line; the stage follows the level
#   cond  "all" (default) | "big": only blocks from S5 on with 4+ Pokemon that have fewer than two Gen 4-9 Pokemon;
#         ":1-3" limits either to tiers 1-3 (1 = the first battle)
# A swap whose new family is already in the block is skipped (running gen49.py again changes nothing).
PLAN = {
    # ---------------- S1 ----------------
    "TOMMY": [("Geodude", "Gigalith")],                      # gym (rock)
    "CALVIN_1": [("Zigzagoon", "Greedent"), ("Breloom", "Gumshoos", "big")],
    "BILLY": [("Zigzagoon", "Toucannon")],
    "TIANA": [("Zigzagoon", "Greedent")],
    "CLARK": [("Machop", "Conkeldurr")],
    "DAWSON": [("Zigzagoon", "Stoutland")],
    "DARIAN": [("Magikarp", "Drednaw")],
    "JOHNSON": [("Lotad", "Diggersby")],
    # ---------------- S2 ----------------
    "TAKAO": [("Machop", "Sawk")],                           # gym (fighting)
    "LAURA": [("Makuhita", "Scrafty")],
    "BRENDEN": [("Meditite", "Grapploct")],
    "LILITH": [("Makuhita", "Throh")],
    "DWAYNE": [("Tentacool", "Lumineon")],
    "JOHANNA": [("Skitty", "Purugly")],
    "HAILEY": [("Goldeen", "Palafin")],
    "CHANDLER": [("Tentacool", "Floatzel")],
    # ---------------- S3 ----------------
    "VIVIAN": [("Meditite", "Pawmot")],                      # gym (electric)
    "DAISY": [("Oddish", "Shiinotic")],
    "ROSE_1": [("Shroomish", "Lilligant"), ("Tropius", "Shiinotic", "big")],
    "EDWARD": [("Spoink", "Musharna")],
    "JACLYN": [("Natu", "Sigilyph")],
    "TIMMY": [("Poochyena", "Thievul")],
    "DALE": [("Tentacool", "Lumineon")],
    "WADE": [("Tentacool", "Barraskewda")],
    "JACOB": [("Voltorb", "Pawmot")],
    "ANTHONY": [("Magnemite", "Luxray")],
    "JASMINE": [("Voltorb", "Zebstrika")],
    "RHETT": [("Machop", "Conkeldurr")],
    "ISABELLE": [("Goldeen", "Palafin")],
    "MELINA": [("Linoone", "Stoutland")],
    # ---------------- S4 ----------------
    "COLE": [("Growlithe", "Volcarona")],                    # gym (fire)
    "KEEGAN": [("Vulpix", "Coalossal")],
    "GERALD": [("Manectric", "Talonflame")],
    "DANIELLE": [("~Gurdurr", "Simisear")],                  # her D-195 Gurdurr wasn't fire
    "WILTON_1": [("Wailmer", "Talonflame", "all:1"), ("Wailmer", "Haxorus", "big:2")],
    "BROOKE_1": [("Wingull", "Purugly", "all:1"), ("Pelipper", "Kilowattrel", "big")],
    "MELISSA": [("Swablu", "Swanna")],
    "SHIRLEY": [("Numel", "Salazzle")],
    "DAISUKE": [("Meditite", "Lucario")],
    "LARRY": [("Nuzleaf", "Toucannon")],
    "AUTUMN": [("Skitty", "Tsareena")],
    "TRAVIS": [("Linoone", "Diggersby")],
    "DILLON": [("Geodude", "Coalossal")],
    "NOLAN": [("Goldeen", "Drednaw")],
    "LAO_1": [("Koffing", "Toxicroak"), ("Koffing", "Skuntank", "big:1-3"), ("Shiftry", "Skuntank", "big:4-5")],
    "LUNG": [("Grimer", "Salazzle")],
    "CAROL": [("Skitty", "Gogoat")],
    "JULIO": [("Voltorb", "Zebstrika")],
    "HAYDEN": [("Vulpix", "Pyroar")],
    "LAWRENCE": [("Baltoy", "Hippowdon")],
    "WYATT": [("Aron", "Rampardos")],
    "BRYANT": [("Vulpix", "Centiskorch")],
    "SHAYLA": [("Shroomish", "Shiinotic")],
    "TRENT_1": [("Geodude", "Coalossal"), ("Geodude", "Gigalith", "big:1-3"), ("Probopass", "Gigalith", "big:4-5")],
    # ---------------- S5 ----------------
    "RANDALL": [("Ninjask", "Staraptor"), ("Linoone", "Stoutland")],   # gym (normal)
    "PARKER": [("Golbat", "Swoobat"), ("Spoink", "Bewear")],
    "GEORGE": [("Wailmer", "Floatzel", "big")],
    "BERKE": [("Sandslash", "Diggersby"), ("Seviper", "Zoroark")],
    "MARY": [("Swablu", "Purugly"), ("Roselia", "Whimsicott")],
    "ALEXIA": [("Aron", "Bouffalant"), ("Baltoy", "Chatot")],
    "JODY": [("Pinsir", "Lokix"), ("Mightyena", "Stoutland")],
    # ---------------- S6 (4+ mons: two each) ----------------
    "JARED": [("Swellow", "Staraptor"), ("Dodrio", "Toucannon")],      # gym (flying)
    "HUMBERTO": [("Swellow", "Hawlucha"), ("Xatu", "Sigilyph")],
    "EDWARDO": [("Noctowl", "Unfezant"), ("Dodrio", "Kilowattrel")],
    "DARIUS": [("Dodrio", "Staraptor"), ("Noctowl", "Swanna")],
    "FLINT": [("Swellow", "Talonflame", "big")],
    "ASHLEY": [("Swablu", "Chatot", "big")],
    "TONY_1": [("Lanturn", "Lumineon", "big")],
    "DONALD": [("Masquerain", "Golisopod", "big")],
    "BARNY": [("Tentacruel", "Barraskewda", "big")],
    "DEMETRIUS": [("Linoone", "Gumshoos", "big")],
    "PERRY": [("Dodrio", "Hawlucha", "big")],
    "PHIL": [("Dodrio", "Unfezant", "big")],
    "YASU": [("Seviper", "Zoroark", "big")],
    "BEVERLY": [("Pelipper", "Kilowattrel", "big")],
    "TARA": [("Staryu", "Lumineon", "big")],
    "DUNCAN": [("Pelipper", "Kilowattrel", "big")],
    "JACKSON_1": [("Tropius", "Toucannon", "big")],
    "CATHERINE_1": [("Gloom", "Tsareena", "big")],
    "GREG": [("Volbeat", "Vespiquen", "big")],
    "ALIX": [("Grumpig", "Swoobat", "big")],
    "FABIAN": [("Magneton", "Luxray", "big")],
    "DAYTON": [("Slugma", "Talonflame", "big")],
    "RACHEL": [("Roselia", "Seismitoad", "big")],
    "FOSTER": [("Nosepass", "Rampardos"), ("Graveler", "Gigalith")],
    "AUSTINA": [("Psyduck", "Bruxish"), ("Lombre", "Swanna")],
    "GWEN": [("Horsea", "Palafin"), ("Chinchou", "Kilowattrel")],
    "CHARLIE": [("Linoone", "Floatzel"), ("Psyduck", "Drednaw")],
    "LUIS": [("Pelipper", "Kilowattrel"), ("Tentacruel", "Barraskewda")],
    "DOMINIK": [("Horsea", "Lumineon"), ("Staryu", "Clawitzer")],
    "MATTHEW": [("Whiscash", "Barraskewda"), ("Pelipper", "Kilowattrel")],
    "KOICHI": [("Meditite", "Throh"), ("Hariyama", "Sawk")],
    "TAYLOR": [("Illumise", "Lokix"), ("Beautifly", "Ribombee")],
    "CARTER": [("Seaking", "Lumineon"), ("Crawdaunt", "Drednaw")],
    "HUGH": [("Swellow", "Toucannon"), ("Pelipper", "Kilowattrel")],
    "TAKASHI": [("Koffing", "Lokix"), ("Swalot", "Hawlucha")],
    "JANI": [("Corsola", "Alomomola"), ("Masquerain", "Dhelmise")],
    "PAULA": [("Meditite", "Lucario"), ("Machoke", "Mienshao")],
    "DENISE": [("Goldeen", "Lumineon"), ("Lanturn", "Alomomola")],
    "CAROLINA": [("Manectric", "Luxray"), ("Roselia", "Tsareena")],
    "ELIJAH": [("Skarmory", "Kilowattrel"), ("Dodrio", "Unfezant")],
    "JAIDEN": [("Koffing", "Thievul"), ("Seviper", "Zoroark")],
    "HELENE": [("Machoke", "Hawlucha"), ("Meditite", "Lucario")],
    # ---------------- S7 ----------------
    "PRESTON": [("Grumpig", "Musharna"), ("Solrock", "Sigilyph")],     # gym (psychic)
    "VIRGIL": [("Claydol", "Bronzong"), ("Gardevoir", "Swoobat")],
    "HANNAH": [("Lunatone", "Sigilyph"), ("Grumpig", "Swoobat")],
    "SAMANTHA": [("Medicham", "Lucario"), ("Claydol", "Bronzong")],
    "MAURA": [("Starmie", "Bruxish"), ("Hypno", "Musharna")],
    "NATE": [("Slowking", "Bronzong"), ("Claydol", "Sigilyph")],
    "KATHLEEN": [("Sableye", "Sigilyph"), ("Dusclops", "Cofagrigus")],
    "CLIFFORD": [("Xatu", "Sigilyph"), ("Starmie", "Bruxish")],
    "NICHOLAS": [("Hypno", "Musharna"), ("Solrock", "Bronzong")],
    "MACEY": [("Grumpig", "Swoobat"), ("Lunatone", "Bronzong")],
    "BLAKE": [("Xatu", "Sigilyph", "big")],
    "SYLVIA": [("Banette", "Musharna", "big")],
    "ALBERTO": [("Swellow", "Toucannon", "big")],
    "ED": [("Kecleon", "Rotom", "big")],
    "FREDRICK": [("Hariyama", "Conkeldurr", "big")],
    "LEAH": [("Grumpig", "Houndstone", "big")],
    "VIOLET": [("Tropius", "Shiinotic", "big")],
    "CHIP": [("Sandslash", "Cofagrigus", "big")],
    "KINDRA": [("Lunatone", "Trevenant", "big")],
    "TAMMY": [("Sableye", "Cofagrigus", "big")],
    "JESSICA_1": [("Kecleon", "Salazzle", "big")],
    "RODNEY": [("Pelipper", "Palafin", "big")],
    "KEVIN": [("Pelipper", "Bruxish", "big")],
    "WALTER_1": [("Golduck", "Pyroar", "big")],
    "ISAIAH_1": [("Tentacruel", "Toxapex", "big")],
    "PRESLEY": [("Pelipper", "Kilowattrel", "big")],
    "ROBERT_1": [("Skarmory", "Corviknight", "big")],
    "CLARISSA": [("Roselia", "Lurantis", "big")],
    "ANGELICA": [("Pelipper", "Swanna"), ("Lanturn", "Seismitoad")],
    "JENNY_1": [("Lanturn", "Lumineon", "big")],
    "DEBRA": [("Pelipper", "Kilowattrel", "big")],
    "LAUREL": [("Luvdisc", "Clawitzer", "big")],
    "JAZMYN": [("Breloom", "Lurantis", "big")],
    "JONAS": [("Seviper", "Zoroark", "big")],
    "KAYLEY": [("Tropius", "Tsareena"), ("Torkoal", "Drifblim")],
    "KELVIN": [("Tentacruel", "Clawitzer", "big")],
    "DAVIS": [("Heracross", "Galvantula", "big")],
    "LORENZO": [("Tropius", "Gogoat", "big")],
    "ATHENA": [("Pelipper", "Swanna", "big")],
    "HARRISON": [("Lanturn", "Palafin", "big")],
    "MAKAYLA": [("Lanturn", "Grapploct", "big")],
    "DARCY": [("Pelipper", "Clawitzer", "big")],
    "CALE": [("Masquerain", "Golisopod", "big")],
    "KEIGO": [("Weezing", "Salazzle", "big")],
    "JONAH": [("Wailmer", "Drednaw", "big")],
    "VALERIE_1": [("Duskull", "Polteageist", "big")],
    "MARCEL": [("Sharpedo", "Barraskewda"), ("Shiftry", "Zoroark")],
    "DECLAN": [("Pelipper", "Kilowattrel"), ("Whiscash", "Wishiwashi")],
    "ZANDER": [("Machoke", "Conkeldurr"), ("Breloom", "Throh")],
    "BRAXTON": [("Swellow", "Staraptor"), ("Wailmer", "Barraskewda")],
    "WENDY": [("Pelipper", "Swanna"), ("Roselia", "Whimsicott")],
    "JENNIFER": [("Roselia", "Trevenant"), ("Lanturn", "Luxray")],
    "MOLLIE": [("Grumpig", "Lucario"), ("Xatu", "Hawlucha")],
    "MARK": [("Loudred", "Tyrantrum"), ("Lairon", "Rampardos")],
    "SPENCER": [("Lanturn", "Lumineon"), ("Sealeo", "Floatzel")],
    "ROLAND": [("Crawdaunt", "Clawitzer"), ("Tentacruel", "Alomomola")],
    "BARRY": [("Tentacruel", "Alomomola"), ("Sharpedo", "Barraskewda")],
    "RICHARD": [("Tentacruel", "Bruxish"), ("Lanturn", "Palafin")],
    "GILBERT": [("Crawdaunt", "Clawitzer"), ("Tentacruel", "Toxapex")],
    "KIYO": [("Machoke", "Mienshao"), ("Hitmontop", "Grapploct")],
    "ATSUSHI": [("Breloom", "Throh"), ("Machoke", "Sawk")],
    "FERNANDO_1": [("Manectric", "Luxray"), ("Ampharos", "Rotom", "big")],
    "JEFFREY_1": [("Surskit", "Golisopod"), ("Dustox", "Volcarona", "big")],
    "VANESSA": [("Chimecho", "Pawmot"), ("Azumarill", "Ribombee")],
    "CAMDEN": [("Pelipper", "Floatzel"), ("Starmie", "Barraskewda")],
    "CHASE": [("Lanturn", "Bruxish"), ("Pelipper", "Palafin")],
    "AARON": [("Vibrava", "Haxorus"), ("Dragonair", "Druddigon")],
    "COLIN": [("Tropius", "Toucannon"), ("Xatu", "Staraptor")],
    "ALEX": [("Pelipper", "Kilowattrel"), ("Skarmory", "Corviknight")],
    "BECK": [("Swellow", "Talonflame"), ("Xatu", "Hawlucha")],
    "TANYA": [("Luvdisc", "Alomomola"), ("Wailmer", "Lumineon")],
    "NIKKI": [("Seaking", "Lumineon"), ("Pelipper", "Swanna")],
    "SIENNA": [("Luvdisc", "Alomomola"), ("Seaking", "Lumineon")],
    "MIU_AND_YUKI": [("Beautifly", "Ribombee"), ("Dustox", "Vespiquen")],
    "AURON": [("Xatu", "Hawlucha"), ("Manectric", "Lucario")],
    "MARLEY": [("Roselia", "Tsareena"), ("Pelipper", "Clawitzer")],
    "REYNA": [("Breloom", "Lucario"), ("Hitmonchan", "Hawlucha")],
    "HUDSON": [("Tentacruel", "Clawitzer"), ("Machoke", "Grapploct")],
    "HENRY": [("Seaking", "Wishiwashi"), ("Sharpedo", "Barraskewda")],
    "ALEXA": [("Lanturn", "Toxapex"), ("Vileplume", "Lilligant")],
    "WAYNE": [("Tentacruel", "Toxapex"), ("Sharpedo", "Bruxish")],
    "AIDAN": [("Swellow", "Staraptor"), ("Xatu", "Toucannon")],
    "LEONEL": [("Whiscash", "Seismitoad"), ("Camerupt", "Pyroar")],
    "CALLIE": [("Machoke", "Lucario"), ("Breloom", "Bewear")],
    "RILEY": [("Sableye", "Zoroark"), ("Weezing", "Skuntank")],
    # ---------------- S8 ----------------
    "DAPHNE": [("Luvdisc", "Lumineon", "big")],                        # gym (water)
    "BRIANNA": [("Golduck", "Floatzel"), ("Lanturn", "Jellicent")],
    "CONNIE": [("Corsola", "Toxapex", "big")],
    "BRIDGET": [("Lanturn", "Lumineon"), ("Corsola", "Barbaracle")],
    "OLIVIA": [("Crawdaunt", "Clawitzer", "big")],
    "TIFFANY": [("Golduck", "Palafin"), ("Relicanth", "Drednaw")],
    "BETHANY": [("Azurill", "Palafin"), ("Sealeo", "Wishiwashi")],
    "ANNIKA": [("Luvdisc", "Alomomola"), ("Lanturn", "Seismitoad")],
    "ANDREA": [("Pelipper", "Swanna"), ("Luvdisc", "Bruxish")],
    "CRISSY": [("Seaking", "Basculin"), ("Pelipper", "Golisopod")],
    "BENNY": [("Xatu", "Toucannon", "big")],
    # ---------------- S9 ----------------
    "ALBERT": [("Skarmory", "Sigilyph", "big")],
    "VITO": [("Dodrio", "Staraptor", "big")],
    "OWEN": [("Golem", "Excadrill", "big")],
    "JULIE": [("Tropius", "Hippowdon", "big")],
    "MITCHELL": [("Xatu", "Sigilyph", "big")],
    "HALLE": [("Houndoom", "Houndstone", "big")],
    "EVERETT": [("Delcatty", "Purugly", "big")],
    "FELIX": [("Claydol", "Golurk"), ("Starmie", "Barbaracle")],
    "EDGAR": [("Manectric", "Luxray"), ("Claydol", "Bronzong")],
    "SAMUEL": [("Tauros", "Bouffalant"), ("Mawile", "Durant")],
    "HOPE": [("Tropius", "Tsareena"), ("Breloom", "Lurantis")],
    "SHANNON": [("Walrein", "Avalugg"), ("Hariyama", "Conkeldurr")],
    "MICHELLE": [("Torkoal", "Coalossal"), ("Crawdaunt", "Clawitzer")],
    "CAROLINE": [("Mawile", "Glimmora"), ("Glalie", "Beartic")],
    # ---------------- POST ----------------
    "LEROY": [("Skarmory", "Corviknight", "big")],
    "MICAH": [("Arcanine", "Pyroar", "big")],
    "THOMAS": [("Swellow", "Braviary", "big")],
    "PHILLIP": [("Sharpedo", "Barraskewda", "big")],
    "VINCENT": [("Medicham", "Lucario"), ("Absol", "Zoroark")],
    "NAOMI": [("Bellossom", "Lilligant"), ("Delcatty", "Purugly")],
    "LEONARD": [("Pelipper", "Floatzel"), ("Machoke", "Conkeldurr")],
    # ---------------- D-195 rematch trainers: the second one in their big tiers ----------------
    "JERRY_1": [("Grumpig", "Musharna", "big")],
    "HALEY_1": [("Delcatty", "Ribombee", "big")],
    "JAMES_1": [("Ninjask", "Lokix", "big")],
    "DALTON_1": [("Electrode", "Rotom", "big")],
    "BENJAMIN_1": [("Electrode", "Zebstrika", "big")],
    "SAWYER_1": [("Torkoal", "Mudsdale", "big")],
    "ETHAN_1": [("Breloom", "Mudsdale", "big")],
    "SHELBY_1": [("Breloom", "Hawlucha", "big")],
    "DUSTY_1": [("Relicanth", "Aurorus", "big")],
    "CINDY_1": [("Azumarill", "Whimsicott", "big")],
    "WINSTON_1": [("Swellow", "Unfezant", "big")],
    "ROBIN": [("Skitty", "Purugly")],
    "DANIELLE": [("~Gurdurr", "Heatmor")],
    "RANDALL": [("Linoone", "Gumshoos"), ("Ninjask", "Vespiquen")],
    # ---------------- Grunts (one each, never the Poochyena / Zubat / Numel / Carvanha lines) ----------------
    "GRUNT_SPACE_CENTER_1": [("Claydol", "Hippowdon")],
    "GRUNT_SPACE_CENTER_2": [("Houndoom", "Pyroar")],
    "GRUNT_SPACE_CENTER_3": [("Weezing", "Salazzle")],
    "GRUNT_SPACE_CENTER_4": [("Sandslash", "Excadrill")],
    "GRUNT_SPACE_CENTER_5": [("Houndoom", "Centiskorch")],
    "GRUNT_SPACE_CENTER_6": [("Magcargo", "Coalossal")],
    "GRUNT_SPACE_CENTER_7": [("Rhydon", "Mudsdale")],
    "GRUNT_MAGMA_HIDEOUT_1": [("Weezing", "Salazzle")],
    "GRUNT_MAGMA_HIDEOUT_2": [("Sandslash", "Excadrill")],
    "GRUNT_MAGMA_HIDEOUT_3": [("Swalot", "Heatmor")],
    "GRUNT_MAGMA_HIDEOUT_4": [("Weezing", "Gigalith")],
    "GRUNT_MAGMA_HIDEOUT_5": [("Graveler", "Coalossal")],
    "GRUNT_MAGMA_HIDEOUT_6": [("Donphan", "Mudsdale")],
    "GRUNT_MAGMA_HIDEOUT_7": [("Muk", "Centiskorch")],
    "GRUNT_MAGMA_HIDEOUT_8": [("Claydol", "Hippowdon")],
    "GRUNT_MAGMA_HIDEOUT_9": [("Torkoal", "Pyroar")],
    "GRUNT_MAGMA_HIDEOUT_10": [("Claydol", "Garganacl")],
    "GRUNT_MAGMA_HIDEOUT_11": [("Weezing", "Krookodile")],
    "GRUNT_MAGMA_HIDEOUT_12": [("Donphan", "Sandaconda")],
    "GRUNT_MAGMA_HIDEOUT_13": [("Claydol", "Rampardos")],
    "GRUNT_MAGMA_HIDEOUT_14": [("Swalot", "Glimmora")],
    "GRUNT_MAGMA_HIDEOUT_15": [("Sandslash", "Hippowdon")],
    "GRUNT_MAGMA_HIDEOUT_16": [("Houndoom", "Talonflame")],
    "GRUNT_WEATHER_INST_1": [("Crawdaunt", "Thievul")],
    "GRUNT_WEATHER_INST_2": [("Crawdaunt", "Barraskewda")],
    "GRUNT_WEATHER_INST_3": [("Sealeo", "Kilowattrel")],
    "GRUNT_WEATHER_INST_4": [("Wailmer", "Floatzel")],
    "GRUNT_WEATHER_INST_5": [("Sealeo", "Zoroark")],
    "GRUNT_MT_PYRE_1": [("Tentacruel", "Clawitzer")],
    "GRUNT_MT_PYRE_2": [("Pelipper", "Kilowattrel")],
    "GRUNT_MT_PYRE_3": [("Crawdaunt", "Skuntank")],
    "GRUNT_MT_PYRE_4": [("Lanturn", "Lumineon")],
    "GRUNT_AQUA_HIDEOUT_1": [("Tentacruel", "Toxapex")],
    "GRUNT_AQUA_HIDEOUT_2": [("Pelipper", "Palafin")],
    "GRUNT_AQUA_HIDEOUT_3": [("Muk", "Skuntank")],
    "GRUNT_AQUA_HIDEOUT_4": [("Lanturn", "Jellicent")],
    "GRUNT_AQUA_HIDEOUT_5": [("Tentacruel", "Barraskewda")],
    "GRUNT_AQUA_HIDEOUT_6": [("Muk", "Scrafty")],
    "GRUNT_AQUA_HIDEOUT_7": [("Crawdaunt", "Clawitzer")],
    "GRUNT_SEAFLOOR_CAVERN_1": [("Crawdaunt", "Barbaracle")],
    "GRUNT_SEAFLOOR_CAVERN_2": [("Muk", "Zoroark")],
    "GRUNT_SEAFLOOR_CAVERN_3": [("Whiscash", "Drednaw")],
    "GRUNT_SEAFLOOR_CAVERN_4": [("Lanturn", "Jellicent")],
    "GRUNT_SEAFLOOR_CAVERN_5": [("Muk", "Toxapex")],
}

# Pre-evolve generic trainers' Pokemon that sit under the D-216 trade-evolution levels:
# block -> [(species, pre-evolution, held item or None)]
FIX = {
    "KIRA_AND_DAN_1": [("Huntail", "Clamperl", "Deep Sea Tooth"), ("Gorebyss", "Clamperl", "Deep Sea Scale")],
    "KIRA_AND_DAN_2": [("Huntail", "Clamperl", "Deep Sea Tooth"), ("Gorebyss", "Clamperl", "Deep Sea Scale")],
    "THALIA_1": [("Gorebyss", "Clamperl", "Deep Sea Scale")],
    "THALIA_2": [("Gorebyss", "Clamperl", "Deep Sea Scale")],
    "THALIA_3": [("Kingdra", "Seadra", None)],
    "NOB_2": [("Machamp", "Machoke", None)],
    "TRENT_2": [("Golem", "Graveler", None)],
    "SAWYER_2": [("Golem", "Graveler", None)],
    "AARON": [("Kingdra", "Seadra", None)],
}
