#!/usr/bin/env python3
"""
report.py - write the trainer table at the end of docs/hack_trainers.md.

  python3 tools/hack/trainers/report.py [--party FILE] [--out FILE]

One row per trainer in tools/hack/trainers/segments.json, grouped by segment: party size, level
range, ace and where the team comes from (tools/hack/trainers/sources.json; story trainers are
"story"), plus the Gen 4-9 species swapped in by round 1 (tools/hack/trainers/gen49_swaps.json,
feedback 1.28). Everything after the "## Trainer table" heading is replaced.
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import party  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
DOC = os.path.join(ROOT, "docs/hack_trainers.md")
HEADING = "## Trainer table"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--party", default=os.path.join(ROOT, "src/data/trainers.party"))
    ap.add_argument("--out", default=DOC, help="the doc to update (default docs/hack_trainers.md)")
    args = ap.parse_args()
    seg = json.load(open(os.path.join(HERE, "segments.json")))
    sources = json.load(open(os.path.join(HERE, "sources.json")))
    swaps = json.load(open(os.path.join(HERE, "gen49_swaps.json")))
    blocks = {tid: party.parse_block(raw) for tid, raw in party.split(open(args.party).read())[1]}
    lines = [HEADING, "<!-- generated by tools/hack/trainers/report.py -->", ""]
    for s, info in seg["segments"].items():
        rows = [(t, v) for t, v in seg["info"].items() if v["segment"] == s and t in blocks]
        if not rows:
            continue
        lines += ["### %s (cap %s) – %s" % (s, info["cap"] if s != "POST" else "none", info["label"]), "",
                  "| Trainer | Map | Role | Mons | Levels | Ace | Source |", "|---|---|---|---|---|---|---|"]
        for t, v in rows:
            mons = blocks[t]["mons"]
            lv = [m["level"] for m in mons]
            role = v["role"] + (" t%d" % v["tier"] if "tier" in v else "")
            src = "story" if v["story"] else sources.get(t, "vanilla")
            if t in swaps:
                src += " + " + ", ".join(s.split(" -> ")[1] for s in swaps[t])
            lines.append("| %s | %s | %s | %d | %d–%d | %s %d | %s |" % (
                t[len("TRAINER_"):], v["map"] or "", role, len(mons), min(lv), max(lv),
                mons[-1]["species"], mons[-1]["level"], src))
        lines.append("")
    text = open(DOC).read()
    text = text[:text.index(HEADING)] + "\n".join(lines)
    open(args.out, "w").write(text)
    print("wrote the trainer table (%d trainers)" % sum(1 for t in seg["info"] if t in blocks))


if __name__ == "__main__":
    main()
